import sunlight
import json
from unidecode import unidecode

legislators = sunlight.congress.all_legislators_in_office()

listOfNames = dict()


#generated by duplicates.py
senateduplicates = []

houseduplicates = ['Collins', 'Rice', 'Green', 'Thompson', 'Ryan', 'Kelly', 'Wilson', 'Smith', 'Brooks', 'Rogers', 'Duncan', 'Maloney', 'Price', 'Murphy', 'Heck', 'Graves', 'Jenkins', 'King', 'Johnson', 'Carter', 'Miller', 'Bishop', 'Brady', 'Davis', 'Sanchez', 'Young', 'Scott']


bothduplicates =  ['Brown', 'Collins', 'Rice', 'Reed', 'Green', 'Thompson', 'Ryan', 'Kelly', 'Wilson', 'Smith', 'Brooks', 'Rogers', 'Duncan', 'Maloney', 'Price', 'Murphy', 'Bishop', 'Heck', 'Graves', 'Jenkins', 'King', 'Johnson', 'Graham', 'Peters', 'Carter', 'Miller', 'Lee', 'Brady', 'Davis', 'Sanchez', 'Young', 'Sessions', 'Scott']



crossduplicates = ['Brown', 'King', 'Reed', 'Lee', 'Johnson', 'Sessions',
'Murphy', 'Peters', 'Scott', 'Collins', 'Graham']

congressNames = dict()
duplicateNames = dict()

for legislator in legislators:
    for element in legislator:
        if isinstance(legislator[element],unicode):
            legislator[element] = unidecode(legislator[element])
    firstlast = legislator['first_name'] + ' ' + legislator['last_name']
    lastfirst = legislator['last_name'] + ' ' + legislator['first_name']
    if legislator['title']=='Rep':
        titlefirstlast = "Representative " + legislator['first_name'] + ' ' + legislator['last_name']
        if legislator['last_name'] in houseduplicates:
            titlelast = ''
            duptitlelast = "Representative " + legislator['last_name']
        else:
            duptitlelast = ''
            titlelast = "Representative " + legislator['last_name']
        if legislator['last_name'] in bothduplicates:
            last = ''
            duplast=legislator['last_name']
        else:
            last = legislator['last_name']
            duplast=''
        if 'middle_name' in legislator and legislator['middle_name'] is not None:
            firstmiddlelast = legislator['first_name'] + ' ' + legislator['middle_name'] + ' ' + legislator['last_name']
        else:
            firstmiddlelast = ''
        if 'suffix' in legislator and legislator['suffix'] is not None:
            suffixname = legislator['first_name'] + ' ' + legislator['last_name'] + ' ' + legislator['suffix'] 
        else:
            suffixname = ''
        if ('nickname' in legislator) and legislator['nickname'] is not None:
            nicklast = legislator['nickname'] + ' ' + legislator['last_name']
        else:
            nicklast = ''

    if legislator['title']=='Sen':
        titlefirstlast = "Senator " + legislator['first_name'] + ' ' + legislator['last_name']
        if legislator['last_name'] in senateduplicates:
            titlelast = ''
            duptitlelast = "Senator " + legislator['last_name']
        else:
            duptitlelast = ''
            titlelast = "Senator " + legislator['last_name']
        if legislator['last_name'] in bothduplicates:
            last = ''
            duplast=legislator['last_name']
        else:
            last = legislator['last_name']
            duplast=''
        if 'middle_name' in legislator and legislator['middle_name'] is not None:
            firstmiddlelast = legislator['first_name'] + ' ' + legislator['middle_name'] + ' ' + legislator['last_name']
        else:
            firstmiddlelast = ''
        if 'suffix' in legislator and legislator['suffix'] is not None:
            suffixname = legislator['first_name'] + ' ' + legislator['last_name'] + ' ' + legislator['suffix'] 
        else:
            suffixname = ''
        if ('nickname' in legislator) and legislator['nickname'] is not None:
            nicklast = legislator['nickname'] + ' ' + legislator['last_name']
        else:
            nicklast = ''

    if legislator['title']=='Del':
        titlefirstlast = "Delegate " + legislator['first_name'] + ' ' + legislator['last_name']
        if legislator['last_name'] in houseduplicates:
            titlelast = ''
            duptitlelast = "Delegate " + legislator['last_name']
        else:
            duptitlelast = ''
            titlelast = "Delegate " + legislator['last_name']
        if legislator['last_name'] in bothduplicates:
            last = ''
            duplast=legislator['last_name']
        else:
            last = legislator['last_name']
            duplast=''
        if 'middle_name' in legislator and legislator['middle_name'] is not None:
            firstmiddlelast = legislator['first_name'] + ' ' + legislator['middle_name'] + ' ' + legislator['last_name']
        else:
            firstmiddlelast = ''
        if 'suffix' in legislator and legislator['suffix'] is not None:
            suffixname = legislator['first_name'] + ' ' + legislator['last_name'] + ' ' + legislator['suffix'] 
        else:
            suffixname = ''
        if ('nickname' in legislator) and legislator['nickname'] is not None:
            nicklast = legislator['nickname'] + ' ' + legislator['last_name']
        else:
            nicklast = ''

    if legislator['title']=='Com':
        titlefirstlast = "Commissioner " + legislator['first_name'] + ' ' + legislator['last_name']
        titlelast = "Commissioner " + legislator['last_name']
        if legislator['last_name'] in houseduplicates:
            titlelast = ''
            duptitlelast = "Commissioner " + legislator['last_name']
        else:
            duptitlelast = ''
            titlelast = "Commissioner " + legislator['last_name']
        if legislator['last_name'] in bothduplicates:
            last = ''
            duplast=legislator['last_name']
        else:
            last = legislator['last_name']
            duplast=''
        if 'middle_name' in legislator and legislator['middle_name'] is not None:
            firstmiddlelast = legislator['first_name'] + ' ' + legislator['middle_name'] + ' ' + legislator['last_name']
        else:
            firstmiddlelast = ''
        if 'suffix' in legislator and legislator['suffix'] is not None:
            suffixname = legislator['first_name'] + ' ' + legislator['last_name'] + ' ' + legislator['suffix'] 
        else:
            suffixname = ''
        if ('nickname' in legislator) and legislator['nickname'] is not None:
            nicklast = legislator['nickname'] + ' ' + legislator['last_name']
        else:
            nicklast = ''

    congressNames[legislator['bioguide_id'].encode('utf-8')] = [(firstlast.encode('utf-8')).lower(),(lastfirst.encode('utf-8')).lower(),(titlefirstlast.encode('utf-8')).lower(),(titlelast.encode('utf-8')).lower(),(last.encode('utf-8')).lower(),(firstmiddlelast.encode('utf-8')).lower(),(suffixname.encode('utf-8')).lower(),(nicklast.encode('utf-8')).lower()]

    duplicateNames[legislator['bioguide_id'].encode('utf-8')] = [(duptitlelast.encode('utf-8')).lower(),(duplast.encode('utf-8')).lower()]

    with open('congressNames.json', 'w') as f:
        json.dump(congressNames, f)

    with open('duplicateNames.json', 'w') as g:
        json.dump(duplicateNames, g)

